/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AndButton {}
}

declare global {


  interface HTMLAndButtonElement extends Components.AndButton, HTMLStencilElement {}
  var HTMLAndButtonElement: {
    prototype: HTMLAndButtonElement;
    new (): HTMLAndButtonElement;
  };
  interface HTMLElementTagNameMap {
    'and-button': HTMLAndButtonElement;
  }
}

declare namespace LocalJSX {
  interface AndButton {}

  interface IntrinsicElements {
    'and-button': AndButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'and-button': LocalJSX.AndButton & JSXBase.HTMLAttributes<HTMLAndButtonElement>;
    }
  }
}


